---
title: "scan-dictionaries"
author: "Steve Simon"
date: "Created 2021-02-06"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This program scans the data dictionaries in the src folder and tallies which fields are used or not used. It was last modified on `r Sys.Date()`. You can find copyright information in the LICENSE file.

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo=FALSE)
suppressMessages(suppressWarnings(library(yaml)))
```

```{r}
flist <- list.files(path="../dd", pattern="*.yaml")
nlist <- NULL
for (fn in flist) {
  y <- read_yaml(paste0("../dd/", fn))
  nlist <- c(nlist, names(y))
}
nlist <- sort(unique(nlist))
for (fn in flist) {
  y <- read_yaml(paste0("../dd/", fn))
  dlist <- setdiff(nlist, names(y))
  if (length(dlist)==0) next
  print(paste0(c(fn, dlist), collapse=", "))
}
```

```{r}
slist <- NULL
for (fn in flist) {
  y <- read_yaml(paste0("../dd/", fn))
  v <- y$vars
    if (length(v)==0) next
  for (i in 1:length(v)) {
    if (length(v[[i]])==0) next
    if ("scale" %in% names(v[[i]])) {slist <- append(slist, v[[i]]$scale)}
  }
}
sort(unique(slist))
```